app_name: Tinder
front_words:    "Be sure to copy /config/settings.yml to /config/settings.local.yml and inserts your secret keys"
admin_user:
    email:              "johnhutch+admin@gmail.com"
    password:           "chester"
    name:               "hutch"
omniauth:
    twitter_key:        ""
    twitter_secret:     ""
    facebook_id:        ""
    facebook_secret:    ""
